name: deploy-manifests

on:
  push:
<<<<<<< HEAD
    branches:
=======
    branches: 
>>>>>>> a1e52cf1388f843ac345c85dac26cf6d9d1b6050
      - master
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketmarket
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
